#!/usr/bin/env python3
"""
JENT Setup Wizard
-----------------
Configures Gmail delivery and uploads your resume.
Run once before starting the agent.

    python setup_wizard.py
"""

import os, sys, shutil, subprocess, smtplib
from pathlib import Path

BASE_DIR = Path(__file__).parent
ENV_FILE  = BASE_DIR / ".env"
ALLOWED_RESUME_EXTS = (".pdf", ".docx", ".doc")

# ANSI colours (work on Windows 10+ / Windows Terminal)
BOLD   = "\033[1m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
CYAN   = "\033[96m"
DIM    = "\033[2m"
RESET  = "\033[0m"

def _h(t):    print(f"\n{BOLD}{CYAN}{t}{RESET}")
def _ok(t):   print(f"  {GREEN}[OK]{RESET}  {t}")
def _warn(t): print(f"  {YELLOW}[!]{RESET}   {t}")
def _err(t):  print(f"  {RED}[ERR]{RESET} {t}")
def _info(t): print(f"  {DIM}{t}{RESET}")

def _prompt(text, default="", secret=False):
    suffix = f" [{default}]" if default else ""
    try:
        if secret:
            import getpass
            val = getpass.getpass(f"  {text}{suffix}: ").strip()
        else:
            val = input(f"  {text}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        val = ""
    return val or default


# --------------------------------------------------------------------------- #
# .env helpers
# --------------------------------------------------------------------------- #

def _load_env() -> dict:
    d = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text("utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            d[k.strip()] = v.strip().strip('"').strip("'")
    return d


def _save_env(data: dict):
    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.write("# JENT credentials - generated by setup_wizard.py\n")
        f.write("# Loaded automatically by job_search_agent.py at startup.\n\n")
        for k, v in data.items():
            f.write(f"{k}={v}\n")
    _ok(f".env saved -> {ENV_FILE}")


def _check_resume() -> Path | None:
    for ext in ALLOWED_RESUME_EXTS:
        p = BASE_DIR / f"resume{ext}"
        if p.exists():
            return p
    return None


# --------------------------------------------------------------------------- #
# Step 1 - Gmail
# --------------------------------------------------------------------------- #

def step_gmail(env: dict):
    _h("Step 1  -  Gmail Delivery")
    print()
    _info("JENT will email you every time it finds a new matching job.")
    _info("You need a Gmail App Password (not your regular password).")
    print()
    _info("How to generate one (takes ~2 minutes):")
    _info("  1. Go to https://myaccount.google.com/apppasswords")
    _info("  2. Sign in, select 'Other' and name it 'JENT'")
    _info("  3. Copy the 16-character password shown")
    print()

    # Pre-fill from existing .env
    existing_addr = env.get("GMAIL_ADDRESS", "")
    existing_pwd  = env.get("GMAIL_APP_PASSWORD", "")

    if existing_addr and existing_pwd:
        _ok(f"Gmail already configured: {existing_addr}")
        change = _prompt("Reconfigure Gmail? (y/N)", "N").lower()
        if change != "y":
            return

    while True:
        addr = _prompt("Your Gmail address", existing_addr)
        if not addr or "@" not in addr:
            _err("Please enter a valid email address.")
            continue

        pwd = _prompt("App password (16 chars, no spaces)", secret=True)
        if not pwd or len(pwd.replace(" ", "")) < 12:
            _err("App password looks too short. Make sure you copy all 16 characters.")
            continue

        pwd = pwd.replace(" ", "")   # strip accidental spaces

        to_addr = _prompt("Send match emails to", addr)
        if not to_addr:
            to_addr = addr

        # Test the credentials live
        print()
        _info("Testing SMTP connection...")
        try:
            with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=10) as srv:
                srv.login(addr, pwd)
            _ok("SMTP login successful!")
            env["GMAIL_ADDRESS"]      = addr
            env["GMAIL_APP_PASSWORD"] = pwd
            env["GMAIL_TO_ADDRESS"]   = to_addr
            env["FORCE_DIRECT_GMAIL"] = "true"
            break
        except smtplib.SMTPAuthenticationError:
            _err("Authentication failed. Check your App Password and make sure")
            _err("2-Step Verification is enabled on your account.")
            retry = _prompt("Try again? (Y/n)", "Y").lower()
            if retry == "n":
                _warn("Gmail skipped. You can add it later in .env")
                break
        except Exception as e:
            _err(f"Connection error: {e}")
            retry = _prompt("Try again? (Y/n)", "Y").lower()
            if retry == "n":
                _warn("Gmail skipped. Add credentials in .env later.")
                break


# --------------------------------------------------------------------------- #
# Step 2 - Resume Upload
# --------------------------------------------------------------------------- #

def step_resume():
    _h("Step 2  -  Resume Upload")
    print()

    existing = _check_resume()
    if existing:
        size_kb = existing.stat().st_size // 1024
        _ok(f"Resume already present: {existing.name}  ({size_kb} KB)")
        change = _prompt("Replace with a different file? (y/N)", "N").lower()
        if change != "y":
            _info("Keeping existing resume.")
            return

    _info("Your resume is used for TF-IDF similarity scoring of job listings.")
    _info("Supported formats: PDF, DOCX")
    print()
    _info("Options:")
    _info("  A) Paste the full path to your resume file")
    _info("  B) Press Enter to skip (use generic keyword fallback)")
    print()

    while True:
        path_raw = _prompt("Path to resume (or Enter to skip)")
        if not path_raw:
            _warn("Skipped - using generic keyword fallback profile.")
            _info("You can upload later via the dashboard at http://localhost:8765")
            break

        # Strip quotes Windows Explorer sometimes adds
        path_str = path_raw.strip('"').strip("'")
        src = Path(path_str)

        if not src.exists():
            _err(f"File not found: {path_str}")
            retry = _prompt("Try a different path? (Y/n)", "Y").lower()
            if retry == "n":
                _warn("Resume skipped.")
                break
            continue

        ext = src.suffix.lower()
        if ext not in ALLOWED_RESUME_EXTS:
            _err(f"Unsupported format '{ext}'. Use .pdf or .docx")
            retry = _prompt("Try a different file? (Y/n)", "Y").lower()
            if retry == "n":
                break
            continue

        # Remove old resume files
        for old_ext in ALLOWED_RESUME_EXTS:
            old = BASE_DIR / f"resume{old_ext}"
            if old.exists():
                old.unlink()

        dest = BASE_DIR / f"resume{ext}"
        try:
            shutil.copy2(src, dest)
            size_kb = dest.stat().st_size // 1024
            _ok(f"Copied to {dest.name}  ({size_kb} KB)")
        except Exception as e:
            _err(f"Copy failed: {e}")
        break


# --------------------------------------------------------------------------- #
# Step 3 - Additional channels (optional)
# --------------------------------------------------------------------------- #
# Step 3 - MongoDB Config (optional)
# --------------------------------------------------------------------------- #

def step_mongodb(env: dict):
    _h("Step 3  -  MongoDB Database Configuration (optional)")
    print()
    _info("MongoDB stores your seen jobs, applied jobs, and cycle history.")
    _info("If skipped, JENT automatically falls back to local JSON files.")
    print()
    use_db = _prompt("Configure custom MongoDB URI? (y/N)", "N").lower()
    if use_db == "y":
        uri = _prompt("MongoDB Connection URI", "mongodb://localhost:27017/jent")
        env["MONGODB_URI"] = uri
        _ok(f"MongoDB URI set to: {uri}")
    else:
        _info("Using default local fallback mode.")


# --------------------------------------------------------------------------- #
# Step 4 - Extra Notification Channels (optional)
# --------------------------------------------------------------------------- #

def step_extra_channels(env: dict):
    _h("Step 4  -  Extra Notification Channels  (optional)")
    print()
    _info("JENT can also ping you on Telegram or Discord alongside Gmail.")
    print()
    add_more = _prompt("Add Telegram or Discord too? (y/N)", "N").lower()
    if add_more != "y":
        return

    print()
    print("  1) Telegram")
    print("  2) Discord")
    print("  3) Both")
    print("  4) Skip")
    choice = _prompt("Choice (1-4)", "4")

    if choice in ("1", "3"):
        _info("Get a token from @BotFather (/newbot), then open your bot and visit")
        _info("https://api.telegram.org/bot<TOKEN>/getUpdates to find your chat_id")
        print()
        token = _prompt("Telegram bot token")
        chat_id = _prompt("Telegram chat_id")
        if token and chat_id:
            env["TELEGRAM_BOT_TOKEN"] = token
            env["TELEGRAM_CHAT_ID"]   = chat_id
            _ok("Telegram configured.")
        else:
            _warn("Skipped Telegram.")

    if choice in ("2", "3"):
        _info("Discord: Server Settings > Integrations > Webhooks > New Webhook > Copy URL")
        print()
        url = _prompt("Discord webhook URL")
        if url:
            env["DISCORD_WEBHOOK_URL"] = url
            _ok("Discord configured.")
        else:
            _warn("Skipped Discord.")


# --------------------------------------------------------------------------- #
# Step 5 - Verify
# --------------------------------------------------------------------------- #

def step_verify():
    _h("Step 5  -  Verification  (dry run)")
    print()
    _info("Running one dry-run cycle to confirm everything is reachable.")
    _info("(Takes 2-3 minutes because Playwright browser scrapers run too.)")
    print()
    go = _prompt("Run verification now? (Y/n)", "Y").lower()
    if go == "n":
        _warn("Skipped. Run manually: python job_search_agent.py --dry-run")
        return

    result = subprocess.run(
        [sys.executable, str(BASE_DIR / "job_search_agent.py"), "--dry-run", "--once"],
        cwd=str(BASE_DIR),
    )
    print()
    if result.returncode == 0:
        _ok("Dry-run completed successfully.")
    else:
        _warn(f"Exited with code {result.returncode}. See log above for details.")


# --------------------------------------------------------------------------- #
# Summary
# --------------------------------------------------------------------------- #

def step_summary(env: dict):
    _h("Setup Complete")
    print()

    # Delivery
    channels = []
    if env.get("GMAIL_ADDRESS"):       channels.append(f"Gmail ({env['GMAIL_ADDRESS']})")
    if env.get("TELEGRAM_BOT_TOKEN"):  channels.append("Telegram")
    if env.get("DISCORD_WEBHOOK_URL"): channels.append("Discord")

    if channels:
        _ok("Delivery: " + ", ".join(channels))
    else:
        _warn("No delivery configured - matches will only appear in the log.")

    r = _check_resume()
    if r:
        _ok(f"Resume: {r.name}")
    else:
        _warn("No resume - using expanded keyword fallback profile")

    print()
    print(f"  {BOLD}Run the agent:{RESET}")
    print(f"    {CYAN}python job_search_agent.py{RESET}           # 24/7 loop (live, emails enabled)")
    print(f"    {CYAN}python job_search_agent.py --once{RESET}    # single live cycle")
    print(f"    {CYAN}python job_search_agent.py --dry-run{RESET} # test only, no emails")
    print()
    print(f"  {BOLD}Dashboard:{RESET}")
    print(f"    {CYAN}python dashboard/app.py{RESET}              # http://localhost:8765")
    print()
    if channels and r:
        print(f"  {GREEN}{BOLD}Everything is configured. You're ready to go!{RESET}")
    else:
        print(f"  {YELLOW}Some optional items are missing - see warnings above.{RESET}")
    print()


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #

def main():
    # Enable ANSI colours on Windows
    try:
        import ctypes
        ctypes.windll.kernel32.SetConsoleMode(
            ctypes.windll.kernel32.GetStdHandle(-11), 7
        )
    except Exception:
        pass

    print(f"\n{BOLD}{CYAN}{'='*50}")
    print(f"  JENT Setup Wizard")
    print(f"{'='*50}{RESET}\n")
    print("  This wizard configures Gmail delivery and your resume.")
    print("  Press Ctrl+C at any time to exit.\n")

    env = _load_env()

    try:
        step_gmail(env)
        if env:
            _save_env(env)

        step_resume()
        step_mongodb(env)
        if env:
            _save_env(env)

        step_extra_channels(env)
        if env:
            _save_env(env)

        step_verify()
        step_summary(env)

    except KeyboardInterrupt:
        print(f"\n\n  {YELLOW}Setup interrupted. Progress saved to .env if any step completed.{RESET}\n")
        if env:
            _save_env(env)
        sys.exit(0)


if __name__ == "__main__":
    main()
